"""
Script to append Section 8 (Hypothesis Testing) to influencer_analysis.ipynb
Run: python add_hypothesis_section.py
"""
import json, os

NB_PATH = 'influencer_analysis.ipynb'

# ── New cells to add ────────────────────────────────────────────────────────
NEW_CELLS = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "---\n",
            "## Section 8: Hypothesis Testing\n",
            "\n",
            "Formal statistical hypothesis tests to validate key business claims from the survey data.\n",
            "\n",
            "We apply non-parametric tests (Mann-Whitney U, Kruskal-Wallis) since ordinal survey data rarely satisfies normality assumptions.\n",
            "\n",
            "| # | Hypothesis | Test | Variables |\n",
            "|---|-----------|------|----------|\n",
            "| H1 | Influencer followers have higher purchase frequency than non-followers | Mann-Whitney U | follows_influencers × purchase_ord |\n",
            "| H2 | Purchase frequency differs significantly across age groups | Kruskal-Wallis ANOVA | age_group × purchase_ord |\n",
            "| H3 | Ad click frequency differs significantly across platforms | Kruskal-Wallis + Dunn | platform × ad_click_ord |\n",
            "| H4 | Average satisfaction score is significantly above neutral (3.0) | One-sample t-test | satisfaction_score |\n",
            "| H5 | Engagement frequency differs between high-spending and low-spending groups | Mann-Whitney U | spending_ord × engagement_ord |"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────\n",
            "# Section 8: Hypothesis Testing\n",
            "# ─────────────────────────────────────────────\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "from scipy import stats\n",
            "from scipy.stats import mannwhitneyu, kruskal, ttest_1samp\n",
            "import warnings\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "# ── Load data (re-use from earlier cells or reload) ─────────────────────────\n",
            "import glob, os\n",
            "candidates = ['influencer_survey.xlsx', 'influencer_survey_clean.xlsx'] + glob.glob('*.xlsx')\n",
            "df_raw = None\n",
            "for path in candidates:\n",
            "    if os.path.exists(path):\n",
            "        try:\n",
            "            df_raw = pd.read_excel(path)\n",
            "            print(f'Loaded: {path}  ({len(df_raw)} rows)')\n",
            "            break\n",
            "        except Exception:\n",
            "            continue\n",
            "\n",
            "if df_raw is None:\n",
            "    print('WARNING: Could not load Excel file. Using synthetic fallback.')\n",
            "    np.random.seed(42)\n",
            "    n = 210\n",
            "    df_raw = pd.DataFrame({\n",
            "        'Age Group': np.random.choice(['13-18','19-24','25-30','31-40','40+'], n),\n",
            "        'Gender': np.random.choice(['Male','Female'], n),\n",
            "        'Average Monthly Online Spending (\\u20b9)': np.random.choice(['< \\u20b9500','\\u20b9500\\u2013\\u20b92000','\\u20b92000\\u2013\\u20b95000','\\u20b95000+'], n),\n",
            "        'Which platforms do you regularly use to consume influencer content': [\n",
            "            ';'.join(np.random.choice(['Instagram','YouTube','Pinterest','Snapchat','Facebook'], size=np.random.randint(1,4), replace=False)) for _ in range(n)],\n",
            "        'Average time spent per day watching influencer-related content': np.random.choice(['Less than 1 hour','1-2 hour','2-4 hour','More than 4 hours'], n),\n",
            "        'Do you currently follow any influencers?': np.random.choice(['Yes','No'], n, p=[0.95,0.05]),\n",
            "        'What factor makes you trust an influencer the most?': np.random.choice(['Content quality','Authenticity','Transparency in reviews','Expertise in niche','High follower count'], n),\n",
            "        'How often do you interact with influencer content (likes, comments, shares, saves)?': np.random.choice(['Rarely','Sometimes','frequently','Almost always'], n),\n",
            "        'To what extent do influencer reviews affect your interest in a product?': np.random.choice([1,2,3,4,5], n),\n",
            "        'Have you ever searched for a product after seeing it promoted by an influencer?': np.random.choice(['Yes','No'], n, p=[0.93,0.07]),\n",
            "        'How often have you purchased a product because of an influencer recommendation?': np.random.choice(['Never','1-2 times','2-3 times','3-2 times','More than 5 times'], n),\n",
            "        'How satisfied were you with products bought through influencer recommendations?': np.random.choice([1,2,3,4,5], n),\n",
            "        'How often do you click on ads shown after engaging with influencer content?': np.random.choice(['Never','Rarely','Sometimes','Frequently'], n),\n",
            "    })\n",
            "\n",
            "# ── Preprocessing ────────────────────────────────────────────────────────────\n",
            "col_map = {\n",
            "    'Age Group': 'age_group',\n",
            "    'Gender': 'gender',\n",
            "    'Average Monthly Online Spending (\\u20b9)': 'spending',\n",
            "    'Which platforms do you regularly use to consume influencer content': 'platforms',\n",
            "    'Average time spent per day watching influencer-related content': 'daily_time',\n",
            "    'Do you currently follow any influencers?': 'follows_influencers',\n",
            "    'What factor makes you trust an influencer the most?': 'trust_factor',\n",
            "    'How often do you interact with influencer content (likes, comments, shares, saves)?': 'engagement_freq',\n",
            "    'To what extent do influencer reviews affect your interest in a product?': 'product_interest_score',\n",
            "    'Have you ever searched for a product after seeing it promoted by an influencer?': 'searched_product',\n",
            "    'How often have you purchased a product because of an influencer recommendation?': 'purchase_freq',\n",
            "    'How satisfied were you with products bought through influencer recommendations?': 'satisfaction_score',\n",
            "    'How often do you click on ads shown after engaging with influencer content?': 'ad_click_freq',\n",
            "}\n",
            "df = df_raw.rename(columns={k: v for k, v in col_map.items() if k in df_raw.columns})\n",
            "\n",
            "spending_map = {'< \\u20b9500': 1, '\\u20b9500\\u2013\\u20b92000': 2, '\\u20b92000\\u2013\\u20b95000': 3, '\\u20b95000+': 4}\n",
            "engage_map   = {'Rarely': 1, 'Sometimes': 2, 'frequently': 3, 'Almost always': 4}\n",
            "purchase_map = {'Never': 0, '1-2 times': 1, '2-3 times': 2, '3-2 times': 3, 'More than 5 times': 4}\n",
            "adclick_map  = {'Never': 0, 'Rarely': 1, 'Sometimes': 2, 'Frequently': 3}\n",
            "age_map      = {'13-18': 1, '19-24': 2, '25-30': 3, '31-40': 4, '40': 5, '40+': 5}\n",
            "\n",
            "if 'spending' in df.columns:         df['spending_ord']     = df['spending'].map(spending_map)\n",
            "if 'engagement_freq' in df.columns:  df['engagement_ord']   = df['engagement_freq'].map(engage_map)\n",
            "if 'purchase_freq' in df.columns:    df['purchase_ord']     = df['purchase_freq'].map(purchase_map)\n",
            "if 'ad_click_freq' in df.columns:    df['ad_click_ord']     = df['ad_click_freq'].map(adclick_map)\n",
            "if 'age_group' in df.columns:        df['age_ord']          = df['age_group'].map(age_map).fillna(2)\n",
            "\n",
            "print('Preprocessing complete. Shape:', df.shape)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "# H1: Mann-Whitney U — Do influencer followers purchase more often?\n",
            "# H0: No difference in purchase frequency between followers and non-followers\n",
            "# H1: Followers have significantly higher purchase frequency\n",
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "\n",
            "h1_results = {}\n",
            "if 'follows_influencers' in df.columns and 'purchase_ord' in df.columns:\n",
            "    followers    = df[df['follows_influencers'] == 'Yes']['purchase_ord'].dropna()\n",
            "    non_followers = df[df['follows_influencers'] == 'No']['purchase_ord'].dropna()\n",
            "\n",
            "    print('H1: Do influencer followers purchase more often than non-followers?')\n",
            "    print(f'  Followers     n={len(followers)}, median={followers.median():.1f}, mean={followers.mean():.2f}')\n",
            "    print(f'  Non-followers n={len(non_followers)}, median={non_followers.median():.1f}, mean={non_followers.mean():.2f}')\n",
            "\n",
            "    if len(followers) > 0 and len(non_followers) > 0:\n",
            "        stat, p = mannwhitneyu(followers, non_followers, alternative='greater')\n",
            "        # Effect size r = Z / sqrt(N)\n",
            "        from scipy.stats import norm\n",
            "        N = len(followers) + len(non_followers)\n",
            "        z = norm.isf(p)\n",
            "        r_effect = z / np.sqrt(N)\n",
            "\n",
            "        h1_results = {\n",
            "            'Hypothesis': 'H1',\n",
            "            'Description': 'Followers purchase more than non-followers',\n",
            "            'Test': 'Mann-Whitney U (one-tailed)',\n",
            "            'Statistic': round(stat, 3),\n",
            "            'p-value': round(p, 5),\n",
            "            'Effect Size (r)': round(r_effect, 3),\n",
            "            'Decision': 'REJECT H0' if p < 0.05 else 'FAIL TO REJECT H0',\n",
            "            'Business Implication': (\n",
            "                'Influencer followers are statistically more likely to make purchases. '\n",
            "                'Campaigns targeting follower audiences have measurably higher conversion potential.'\n",
            "                if p < 0.05 else\n",
            "                'No statistically significant difference detected. Non-follower audiences may also convert effectively.'\n",
            "            )\n",
            "        }\n",
            "        print(f'  Mann-Whitney U = {stat:.3f}, p = {p:.5f}')\n",
            "        print(f'  Effect size r = {r_effect:.3f}')\n",
            "        print(f'  Decision: {h1_results[\"Decision\"]} (alpha=0.05)')\n",
            "        print(f'  Implication: {h1_results[\"Business Implication\"]}')\n",
            "    else:\n",
            "        print('  Insufficient data for H1 test.')\n",
            "else:\n",
            "    print('  Required columns not found for H1.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "# H2: Kruskal-Wallis — Does purchase frequency differ across age groups?\n",
            "# H0: All age groups have the same purchase frequency distribution\n",
            "# H1: At least one age group has a significantly different purchase frequency\n",
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "\n",
            "h2_results = {}\n",
            "if 'age_group' in df.columns and 'purchase_ord' in df.columns:\n",
            "    age_groups = df.dropna(subset=['age_group','purchase_ord'])\n",
            "    groups_h2 = [g['purchase_ord'].values for _, g in age_groups.groupby('age_group') if len(g) >= 5]\n",
            "    group_names = [name for name, g in age_groups.groupby('age_group') if len(g) >= 5]\n",
            "\n",
            "    print('H2: Does purchase frequency differ across age groups?')\n",
            "    for name, g in age_groups.groupby('age_group'):\n",
            "        print(f'  {name}: n={len(g)}, median={g[\"purchase_ord\"].median():.1f}, mean={g[\"purchase_ord\"].mean():.2f}')\n",
            "\n",
            "    if len(groups_h2) >= 2:\n",
            "        stat_h2, p_h2 = kruskal(*groups_h2)\n",
            "        n_total = sum(len(g) for g in groups_h2)\n",
            "        k = len(groups_h2)\n",
            "        eta_sq = (stat_h2 - k + 1) / (n_total - k)  # eta-squared approximation\n",
            "\n",
            "        h2_results = {\n",
            "            'Hypothesis': 'H2',\n",
            "            'Description': 'Purchase frequency differs across age groups',\n",
            "            'Test': 'Kruskal-Wallis H',\n",
            "            'Statistic': round(stat_h2, 3),\n",
            "            'p-value': round(p_h2, 5),\n",
            "            'Effect Size (η²)': round(max(eta_sq, 0), 3),\n",
            "            'Decision': 'REJECT H0' if p_h2 < 0.05 else 'FAIL TO REJECT H0',\n",
            "            'Business Implication': (\n",
            "                'Significant age-based differences in purchase behavior exist. '\n",
            "                'Segment influencer campaigns by age group with tailored messaging and product categories.'\n",
            "                if p_h2 < 0.05 else\n",
            "                'No significant age-based differences. A uniform campaign strategy can be deployed across age segments.'\n",
            "            )\n",
            "        }\n",
            "        print(f'  Kruskal-Wallis H = {stat_h2:.3f}, p = {p_h2:.5f}')\n",
            "        print(f'  Effect size \\u03b7\\u00b2 \\u2248 {max(eta_sq,0):.3f}')\n",
            "        print(f'  Decision: {h2_results[\"Decision\"]} (alpha=0.05)')\n",
            "        print(f'  Implication: {h2_results[\"Business Implication\"]}')\n",
            "    else:\n",
            "        print('  Insufficient age group data for H2.')\n",
            "else:\n",
            "    print('  Required columns not found for H2.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "# H3: Kruskal-Wallis — Does ad click frequency differ across platforms?\n",
            "# H0: Ad click frequency is the same across all platforms\n",
            "# H1: At least one platform group has significantly different ad click frequency\n",
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "\n",
            "h3_results = {}\n",
            "platform_list_h3 = ['Instagram', 'YouTube', 'Pinterest', 'Snapchat', 'Facebook']\n",
            "\n",
            "if 'platforms' in df.columns and 'ad_click_ord' in df.columns:\n",
            "    groups_h3 = []\n",
            "    group_names_h3 = []\n",
            "    print('H3: Does ad click frequency differ across platforms?')\n",
            "    for plat in platform_list_h3:\n",
            "        mask = df['platforms'].str.contains(plat, na=False)\n",
            "        grp = df[mask]['ad_click_ord'].dropna()\n",
            "        if len(grp) >= 5:\n",
            "            groups_h3.append(grp.values)\n",
            "            group_names_h3.append(plat)\n",
            "            print(f'  {plat}: n={len(grp)}, median={grp.median():.1f}, mean={grp.mean():.2f}')\n",
            "\n",
            "    if len(groups_h3) >= 2:\n",
            "        stat_h3, p_h3 = kruskal(*groups_h3)\n",
            "        n_total_h3 = sum(len(g) for g in groups_h3)\n",
            "        k_h3 = len(groups_h3)\n",
            "        eta_sq_h3 = (stat_h3 - k_h3 + 1) / (n_total_h3 - k_h3)\n",
            "\n",
            "        h3_results = {\n",
            "            'Hypothesis': 'H3',\n",
            "            'Description': 'Ad click frequency differs across platforms',\n",
            "            'Test': 'Kruskal-Wallis H',\n",
            "            'Statistic': round(stat_h3, 3),\n",
            "            'p-value': round(p_h3, 5),\n",
            "            'Effect Size (η²)': round(max(eta_sq_h3, 0), 3),\n",
            "            'Decision': 'REJECT H0' if p_h3 < 0.05 else 'FAIL TO REJECT H0',\n",
            "            'Business Implication': (\n",
            "                'Platforms differ significantly in ad click-through. '\n",
            "                'Allocate retargeting budget to high-click platforms; avoid wasting spend on low-response channels.'\n",
            "                if p_h3 < 0.05 else\n",
            "                'No significant platform difference in ad clicks. Multi-platform budget can be allocated proportionally by reach.'\n",
            "            )\n",
            "        }\n",
            "        print(f'  Kruskal-Wallis H = {stat_h3:.3f}, p = {p_h3:.5f}')\n",
            "        print(f'  Effect size \\u03b7\\u00b2 \\u2248 {max(eta_sq_h3,0):.3f}')\n",
            "        print(f'  Decision: {h3_results[\"Decision\"]} (alpha=0.05)')\n",
            "        print(f'  Implication: {h3_results[\"Business Implication\"]}')\n",
            "    else:\n",
            "        print('  Insufficient platform group data for H3.')\n",
            "else:\n",
            "    print('  Required columns not found for H3.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "# H4: One-Sample t-test — Is avg satisfaction significantly above neutral (3.0)?\n",
            "# H0: Population mean satisfaction = 3.0 (neutral)\n",
            "# H1: Population mean satisfaction > 3.0\n",
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "\n",
            "h4_results = {}\n",
            "NEUTRAL = 3.0\n",
            "if 'satisfaction_score' in df.columns:\n",
            "    sat = df['satisfaction_score'].dropna()\n",
            "    print(f'H4: Is average satisfaction significantly above neutral ({NEUTRAL})?')\n",
            "    print(f'  n={len(sat)}, mean={sat.mean():.3f}, std={sat.std():.3f}, median={sat.median():.1f}')\n",
            "\n",
            "    stat_h4, p_h4_two = ttest_1samp(sat, NEUTRAL)\n",
            "    p_h4 = p_h4_two / 2 if stat_h4 > 0 else 1.0   # one-tailed p\n",
            "    cohens_d = (sat.mean() - NEUTRAL) / sat.std()\n",
            "\n",
            "    h4_results = {\n",
            "        'Hypothesis': 'H4',\n",
            "        'Description': f'Mean satisfaction > {NEUTRAL} (neutral)',\n",
            "        'Test': 'One-sample t-test (one-tailed)',\n",
            "        'Statistic': round(stat_h4, 3),\n",
            "        'p-value': round(p_h4, 5),\n",
            "        \"Effect Size (Cohen's d)\": round(cohens_d, 3),\n",
            "        'Decision': 'REJECT H0' if p_h4 < 0.05 else 'FAIL TO REJECT H0',\n",
            "        'Business Implication': (\n",
            "            f'Influencer-driven purchases yield significantly above-neutral satisfaction (mean={sat.mean():.2f}). '\n",
            "            'This validates influencer marketing as a satisfying pathway — brands should amplify review content.'\n",
            "            if p_h4 < 0.05 else\n",
            "            'Satisfaction is not significantly above neutral. Quality of influencer-recommended products needs improvement.'\n",
            "        )\n",
            "    }\n",
            "    print(f'  t = {stat_h4:.3f}, p (one-tailed) = {p_h4:.5f}')\n",
            "    print(f\"  Cohen's d = {cohens_d:.3f} ({'large' if abs(cohens_d)>0.8 else 'medium' if abs(cohens_d)>0.5 else 'small'} effect)\")\n",
            "    print(f'  Decision: {h4_results[\"Decision\"]} (alpha=0.05)')\n",
            "    print(f'  Implication: {h4_results[\"Business Implication\"]}')\n",
            "else:\n",
            "    print('  satisfaction_score column not found for H4.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "# H5: Mann-Whitney U — Do high-spenders engage more frequently?\n",
            "# H0: No difference in engagement frequency between high and low spenders\n",
            "# H1: High-spenders (₹2000+) engage significantly more\n",
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "\n",
            "h5_results = {}\n",
            "if 'spending_ord' in df.columns and 'engagement_ord' in df.columns:\n",
            "    high_spenders = df[df['spending_ord'] >= 3]['engagement_ord'].dropna()\n",
            "    low_spenders  = df[df['spending_ord'] <= 2]['engagement_ord'].dropna()\n",
            "\n",
            "    print('H5: Do high-spenders (\\u20b92000+) engage more than low-spenders?')\n",
            "    print(f'  High spenders (\\u20b92000+): n={len(high_spenders)}, median={high_spenders.median():.1f}, mean={high_spenders.mean():.2f}')\n",
            "    print(f'  Low spenders  (<\\u20b92000):   n={len(low_spenders)}, median={low_spenders.median():.1f}, mean={low_spenders.mean():.2f}')\n",
            "\n",
            "    if len(high_spenders) > 0 and len(low_spenders) > 0:\n",
            "        from scipy.stats import norm\n",
            "        stat_h5, p_h5 = mannwhitneyu(high_spenders, low_spenders, alternative='greater')\n",
            "        N_h5 = len(high_spenders) + len(low_spenders)\n",
            "        z_h5 = norm.isf(p_h5)\n",
            "        r_h5 = z_h5 / np.sqrt(N_h5)\n",
            "\n",
            "        h5_results = {\n",
            "            'Hypothesis': 'H5',\n",
            "            'Description': 'High-spenders engage more than low-spenders',\n",
            "            'Test': 'Mann-Whitney U (one-tailed)',\n",
            "            'Statistic': round(stat_h5, 3),\n",
            "            'p-value': round(p_h5, 5),\n",
            "            'Effect Size (r)': round(r_h5, 3),\n",
            "            'Decision': 'REJECT H0' if p_h5 < 0.05 else 'FAIL TO REJECT H0',\n",
            "            'Business Implication': (\n",
            "                'Higher spending is significantly associated with higher engagement. '\n",
            "                'Premium influencer campaigns should explicitly target high-spending consumer segments.'\n",
            "                if p_h5 < 0.05 else\n",
            "                'No significant engagement difference across spending groups. '\n",
            "                'Engagement is not a reliable proxy for spending capacity.'\n",
            "            )\n",
            "        }\n",
            "        print(f'  Mann-Whitney U = {stat_h5:.3f}, p = {p_h5:.5f}')\n",
            "        print(f'  Effect size r = {r_h5:.3f}')\n",
            "        print(f'  Decision: {h5_results[\"Decision\"]} (alpha=0.05)')\n",
            "        print(f'  Implication: {h5_results[\"Business Implication\"]}')\n",
            "    else:\n",
            "        print('  Insufficient data for H5.')\n",
            "else:\n",
            "    print('  Required columns not found for H5.')\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "# Consolidated Hypothesis Testing Summary Table\n",
            "# ─────────────────────────────────────────────────────────────────────────────\n",
            "import pandas as pd\n",
            "import matplotlib.pyplot as plt\n",
            "import matplotlib.patches as mpatches\n",
            "\n",
            "all_results = [r for r in [h1_results, h2_results, h3_results, h4_results, h5_results] if r]\n",
            "\n",
            "if all_results:\n",
            "    summary_df = pd.DataFrame(all_results)\n",
            "    display_cols = ['Hypothesis', 'Description', 'Test', 'Statistic', 'p-value', 'Decision', 'Business Implication']\n",
            "    display_cols = [c for c in display_cols if c in summary_df.columns]\n",
            "\n",
            "    print('\\n' + '='*90)\n",
            "    print('HYPOTHESIS TESTING SUMMARY TABLE')\n",
            "    print('='*90)\n",
            "    print(summary_df[display_cols].to_string(index=False, max_colwidth=60))\n",
            "    print('='*90 + '\\n')\n",
            "\n",
            "    # Save results to CSV\n",
            "    summary_df.to_csv('hypothesis_results.csv', index=False)\n",
            "    print('Results exported to: hypothesis_results.csv')\n",
            "\n",
            "    # ── Visualization: p-value bar chart ──────────────────────────────────────\n",
            "    PALETTE = ['#7c5cfc','#fc5c7d','#5cf0c8','#fca95c','#5c96f0']\n",
            "    plt.rcParams.update({\n",
            "        'figure.facecolor': '#111118', 'axes.facecolor': '#16161f',\n",
            "        'axes.edgecolor': '#3a3a5c', 'axes.labelcolor': '#c8c8e8',\n",
            "        'xtick.color': '#8888aa', 'ytick.color': '#8888aa',\n",
            "        'text.color': '#e8e8f0', 'grid.color': '#2a2a3a',\n",
            "    })\n",
            "\n",
            "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
            "    fig.suptitle('Section 8: Hypothesis Testing Results', fontsize=13, fontweight='bold')\n",
            "\n",
            "    # p-values chart\n",
            "    hyps   = summary_df['Hypothesis'].tolist()\n",
            "    pvals  = summary_df['p-value'].tolist()\n",
            "    colors = ['#5cf0c8' if p < 0.05 else '#fc5c7d' for p in pvals]\n",
            "    bars = axes[0].barh(hyps, pvals, color=colors, edgecolor='#0a0a0f', alpha=0.88)\n",
            "    axes[0].axvline(0.05, color='white', linestyle='--', linewidth=1.5, label='α = 0.05')\n",
            "    axes[0].set_title('p-values per Hypothesis\\n(green = reject H0, red = fail to reject)', fontweight='bold')\n",
            "    axes[0].set_xlabel('p-value')\n",
            "    axes[0].bar_label(bars, fmt='%.4f', fontsize=9, padding=3)\n",
            "    axes[0].legend(fontsize=9)\n",
            "\n",
            "    # Decision summary\n",
            "    decisions = summary_df['Decision'].tolist()\n",
            "    reject_count  = decisions.count('REJECT H0')\n",
            "    fail_count    = decisions.count('FAIL TO REJECT H0')\n",
            "    wedge_vals    = [reject_count, fail_count]\n",
            "    wedge_labels  = [f'Reject H0\\n(n={reject_count})', f'Fail to Reject\\n(n={fail_count})']\n",
            "    wedge_colors  = ['#5cf0c8', '#fc5c7d']\n",
            "    if sum(wedge_vals) > 0:\n",
            "        axes[1].pie(wedge_vals, labels=wedge_labels, colors=wedge_colors, autopct='%1.0f%%',\n",
            "                    startangle=90, wedgeprops={'edgecolor':'#0a0a0f','linewidth':2})\n",
            "    axes[1].set_title('H0 Decision Summary', fontweight='bold')\n",
            "\n",
            "    plt.tight_layout()\n",
            "    plt.savefig('fig_15_hypothesis_testing.png', dpi=150, bbox_inches='tight')\n",
            "    plt.show()\n",
            "    print('Figure saved: fig_15_hypothesis_testing.png')\n",
            "else:\n",
            "    print('No hypothesis results available to display.')\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "### Section 8 Summary: Hypothesis Testing Findings\n",
            "\n",
            "| Hypothesis | Description | Decision | Business Action |\n",
            "|------------|-------------|----------|-----------------|\n",
            "| H1 | Followers purchase more than non-followers | ✅/❌ | Target follower audiences for conversion campaigns |\n",
            "| H2 | Purchase frequency differs across age groups | ✅/❌ | Segment campaigns by age with tailored content |\n",
            "| H3 | Ad click frequency differs across platforms | ✅/❌ | Reallocate retargeting budget to high-click platforms |\n",
            "| H4 | Avg satisfaction > neutral (3.0) | ✅/❌ | Amplify review content as satisfaction signal |\n",
            "| H5 | High-spenders engage more than low-spenders | ✅/❌ | Target premium campaigns at high-spending segments |\n",
            "\n",
            "> **Key Takeaway**: Statistical hypothesis testing provides rigorous justification for campaign decisions beyond descriptive statistics. The Mann-Whitney U tests are appropriate for ordinal data; the one-sample t-test assumes approximate normality for satisfaction scores.\n",
            "\n",
            "**Output files:**\n",
            "- `hypothesis_results.csv` — full results table\n",
            "- `fig_15_hypothesis_testing.png` — visual summary"
        ]
    }
]

# ── Load existing notebook ────────────────────────────────────────────────────
if not os.path.exists(NB_PATH):
    print(f"ERROR: Notebook not found at {NB_PATH}")
    exit(1)

with open(NB_PATH, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── Append new cells ──────────────────────────────────────────────────────────
original_count = len(nb['cells'])
nb['cells'].extend(NEW_CELLS)

with open(NB_PATH, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"SUCCESS: Added {len(NEW_CELLS)} new cells to {NB_PATH}")
print(f"  Before: {original_count} cells  |  After: {len(nb['cells'])} cells")
print("  Section 8 (Hypothesis Testing) appended successfully.")
